### ISSUE TITLE
[BUG] - Wilcard issue

### ISSUE THREAD

**Issue by burny0202** [zaneschepke/wgtunnel#427]
**Describe the bug**

Wildcards don't seem to be functioning correctly. 

I have two access points _7_ and _8_

Adding one also whitelists the other

**Smartphone (please complete the following information):**
Multiple android devices. Android 5.1 + 

**To Reproduce**

Add _7_ as a whitelisted access point. 
Don't add _8_
Connect to _8_.
Tunnel is not brought up

**Expected behavior**

Tunnel is brought up

Great app - Appreciate all the hard work on this.

**Comment by zaneschepke** [comment]
Hello! I've changes wildcards so it is now a toggle option to prevent it from breaking people who have special characters that accidentally get translated as regex. 

I also updated the docs for how to use these wildcards as (when they are enabled) certain special characters need to be escaped for them to work properly. Please check it out and let me know if you have any problems, but I believe this should fix the wildcard issues. If not, we can reopen. 

https://zaneschepke.com/wgtunnel-docs/features.html#wildcard-wi-fi-name-support

**Comment by burny0202** [comment]
Loving the new UI - Looking great

Unfortantely even with the switch I still see the same behavior. 

Adding AP _7_ as the only trusted one, while connected to _8_  - The tunnel still goes down - Even if I add it while connected to VPN

Thanks again for all your hard work with this great app

**Comment by burny0202** [comment]
@zaneschepke - Can you reopen?
